
name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Automation/requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pytest Automation/tests -q --html=Automation/reports/report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: Automation/reports/report.html
